const skinDefs=[
["Glock-18 | Water Elemental",80,"#d32ce6"],["Glock-18 | Vogue",110,"#d32ce6"],["USP-S | Cortex",140,"#d32ce6"],["USP-S | The Traitor",190,"#eb4b4b"],["P250 | See Ya Later",220,"#eb4b4b"],["Desert Eagle | Mecha Industries",260,"#eb4b4b"],["Desert Eagle | Printstream",320,"#eb4b4b"],["Five-SeveN | Hyper Beast",360,"#eb4b4b"],
["MP9 | Starlight Protector",410,"#eb4b4b"],["MAC-10 | Neon Rider",460,"#eb4b4b"],["UMP-45 | Primal Saber",510,"#d32ce6"],["P90 | Asiimov",570,"#eb4b4b"],["MP7 | Bloodsport",630,"#eb4b4b"],["FAMAS | Commemoration",700,"#eb4b4b"],["Galil AR | Chatterbox",780,"#eb4b4b"],["AUG | Akihabara Accept",870,"#eb4b4b"],
["M4A4 | Neo-Noir",970,"#eb4b4b"],["AK-47 | Asiimov",1080,"#eb4b4b"],["M4A1-S | Hyper Beast",1200,"#eb4b4b"],["AWP | Asiimov",1350,"#eb4b4b"],["AK-47 | Neon Rider",1520,"#eb4b4b"],["M4A1-S | Printstream",1720,"#eb4b4b"],["M4A4 | The Emperor",1950,"#eb4b4b"],["AK-47 | Bloodsport",2200,"#eb4b4b"],
["AWP | Containment Breach",2500,"#eb4b4b"],["AK-47 | Vulcan",2850,"#eb4b4b"],["M4A1-S | Blue Phosphor",3250,"#eb4b4b"],["AWP | Lightning Strike",3700,"#eb4b4b"],["AK-47 | Fire Serpent",4200,"#eb4b4b"],["AWP | Fade",4800,"#eb4b4b"],["M4A4 | Poseidon",5500,"#eb4b4b"],["M4A4 | Howl",6500,"#e4ae39"],
["★ Navaja Knife | Doppler",7200,"#e4ae39"],["★ Gut Knife | Gamma Doppler",8000,"#e4ae39"],["★ Falchion Knife | Fade",9000,"#e4ae39"],["★ Huntsman Knife | Doppler",10000,"#e4ae39"],["★ Bayonet | Doppler",11500,"#e4ae39"],["★ Flip Knife | Gamma Doppler",13000,"#e4ae39"],["★ Karambit | Doppler",15500,"#e4ae39"],["★ Butterfly Knife | Fade",18000,"#e4ae39"],
["AWP | Dragon Lore",21000,"#e4ae39"],["AK-47 | Wild Lotus",24000,"#e4ae39"],["AWP | Gungnir",28000,"#e4ae39"],["★ Karambit | Fade",32000,"#e4ae39"],["★ Butterfly Knife | Doppler",36000,"#e4ae39"],["★ M9 Bayonet | Gamma Doppler",40000,"#e4ae39"],["★ Sport Gloves | Vice",45000,"#e4ae39"],["★ Specialist Gloves | Crimson Kimono",50000,"#e4ae39"]
];let items=skinDefs.map(([n,p,color])=>({n,p,color,img:""}));const API="https://raw.githubusercontent.com/ByMykel/CSGO-API/main/public/api/en/skins.json";const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
let raw=JSON.parse(localStorage.getItem("nexup")||"null");let state=raw||{balance:2500,inventory:[items[0],items[1],items[2]],history:[]};if(state.inventory?.some(x=>!skinDefs.some(d=>d[0]===x.n))){state.inventory=[items[0],items[1],items[2]];state.balance=Math.max(state.balance||0,2500)}
let source=0,target=3,busy=false,needleRotation=0;const save=()=>localStorage.setItem("nexup",JSON.stringify(state)),money=n=>n.toLocaleString("ru-RU")+" ◆";
function syncItem(x){let y=items.find(i=>i.n===x.n);return y?{...y}:x}state.inventory=(state.inventory||[]).map(syncItem);
function card(x,shop=false){x=syncItem(x);let visual=x.img?'<img class="skin-img" src="'+x.img+'" alt="'+x.n+'">':'<div class="item-icon">🔫</div>';return '<i class="rarity" style="color:'+x.color+';background:'+x.color+'"></i>'+visual+'<div class="item-name">'+x.n+'</div><div class="price">'+money(x.p)+'</div>'+(shop?'<button class="buy">КУПИТЬ</button>':'')}
function chance(){return state.inventory.length?Math.min(90,Math.max(3,state.inventory[source].p/items[target].p*92)):0}function toast(t){$("#toast").textContent=t;$("#toast").classList.add("show");setTimeout(()=>$("#toast").classList.remove("show"),1800)}
function render(){state.inventory=state.inventory.map(syncItem);if(state.inventory.length){source=Math.min(source,state.inventory.length-1);$("#sourceCard").innerHTML=card(state.inventory[source]);$("#upgradeBtn").disabled=busy}else{$("#sourceCard").innerHTML='<div class="item-icon">📭</div><div class="item-name">Инвентарь пуст</div><div class="price">Зайди в магазин</div>';$("#upgradeBtn").disabled=true}$("#targetCard").innerHTML=card(items[target]);let c=chance();$("#chance").textContent=c.toFixed(1)+"%";$("#wheel").style.background='conic-gradient(from 0deg,var(--lime) 0 '+c+'%,#252934 '+c+'% 100%)';$("#balance").textContent=state.balance.toLocaleString("ru-RU");$("#invCount").textContent=state.inventory.length;$("#market").innerHTML=items.slice(2).map(x=>'<div class="card" data-target="'+items.indexOf(x)+'">'+card(x)+'</div>').join("");$("#shopGrid").innerHTML=items.map((x,i)=>'<div class="card" data-buy="'+i+'">'+card(x,true)+'</div>').join("");$("#inventoryGrid").innerHTML=state.inventory.length?state.inventory.map((x,i)=>'<div class="card" data-source="'+i+'">'+card(x)+'</div>').join(""):'<p>Пусто. Используй аварийный набор или магазин.</p>';$("#historyList").innerHTML=state.history.length?state.history.map(h=>'<div class="history-row"><div><b>'+h.from+' → '+h.to+'</b><br><small>'+h.time+'</small></div><strong class="'+(h.ok?"win":"lose")+'">'+(h.ok?"УСПЕХ":"НЕУДАЧА")+'</strong></div>').join(""):'<p>История пока пуста.</p>';$("[data-tab=shop]").innerHTML="🛒 Магазин";$$("[data-target]").forEach(e=>e.onclick=()=>{target=+e.dataset.target;render()});$$("[data-buy]").forEach(e=>e.onclick=()=>buy(+e.dataset.buy));$$("[data-source]").forEach(e=>e.onclick=()=>{source=+e.dataset.source;tab("upgrade")})}
async function loadSkins(){try{let data=await fetch(API).then(r=>r.json());for(let item of items){let s=data.find(v=>v.name===item.n);if(s){item.img=s.image;item.color=s.rarity?.color||item.color}}state.inventory=state.inventory.map(syncItem);save();render()}catch(e){console.warn("CS2 images fallback",e)}}function buy(i){let x=items[i];if(state.balance<x.p)return toast("Недостаточно демо-кредитов");state.balance-=x.p;state.inventory.push({...x});save();render();toast(x.n+" добавлен в инвентарь")}
function tab(id){$$(".tab,nav button").forEach(x=>x.classList.remove("active"));$("#"+id).classList.add("active");let b=document.querySelector('[data-tab="'+id+'"]');if(b)b.classList.add("active");render()}$$("nav button").forEach(b=>b.onclick=()=>tab(b.dataset.tab));$("#prevSource").onclick=()=>{if(state.inventory.length){source=(source-1+state.inventory.length)%state.inventory.length;render()}};$("#nextSource").onclick=()=>{if(state.inventory.length){source=(source+1)%state.inventory.length;render()}};$("#prevTarget").onclick=()=>{target=(target-1+items.length)%items.length;render()};$("#nextTarget").onclick=()=>{target=(target+1)%items.length;render()};
$("#rescue").onclick=()=>{if(state.inventory.length||state.balance>=300)return toast("Набор доступен, когда почти всё потеряно");state.balance+=1000;state.inventory.push({...items[0]},{...items[1]});save();render();toast("Аварийный набор: 1000 ◆ + 2 CS2 скина")};
function particles(){for(let i=0;i<34;i++){let p=document.createElement("i");p.className="particle";p.style.left=(45+Math.random()*10)+"vw";p.style.top="45vh";p.style.background=i%2?"#c6ff3d":"#fff";p.style.setProperty("--dx",(Math.random()*500-250)+"px");p.style.setProperty("--dy",(150+Math.random()*350)+"px");p.style.setProperty("--rot",(Math.random()*900-450)+"deg");document.body.appendChild(p);setTimeout(()=>p.remove(),1200)}}
$("#upgradeBtn").onclick=()=>{if(busy||!state.inventory.length)return;busy=true;let from=syncItem(state.inventory[source]),to=items[target],c=chance(),landing=Math.random()*360,ok=landing<(c/100*360),turns=7+Math.floor(Math.random()*3);needleRotation+=turns*360+((landing-(needleRotation%360)+360)%360);$("#result").className="result";$("#result").textContent="АПГРЕЙД...";$("#wheel").classList.add("running");$("#needle").classList.add("spinning");$("#needle").style.transition="transform 3.25s cubic-bezier(.08,.72,.12,1)";$("#needle").style.transform="rotate("+needleRotation+"deg)";render();setTimeout(()=>{$("#wheel").classList.remove("running");$("#needle").classList.remove("spinning");let arena=$(".arena");if(ok){state.inventory[source]={...to};$("#result").textContent="УСПЕХ · "+to.n;$("#result").className="result win";arena.classList.add("win-flash");particles()}else{state.inventory.splice(source,1);source=0;$("#result").textContent="НЕУДАЧА · СКИН ПОТЕРЯН";$("#result").className="result lose";arena.classList.add("lose-flash")}state.history.unshift({from:from.n,to:to.n,ok,time:new Date().toLocaleString("ru-RU")});state.history=state.history.slice(0,30);busy=false;save();render();if(ok){$("#targetCard").classList.add("skin-reveal")}setTimeout(()=>{arena.classList.remove("win-flash","lose-flash");$("#targetCard").classList.remove("skin-reveal")},900)},3300)};render();loadSkins();